version: 2.1

executors:
  small:
    resource_class: small
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      JVM_OPTS: -Xmx4G

jobs:
  build:
    executor: small
    steps:
      - checkout

      - restore_cache:
          keys:
            - "bla-{{ .Revision }}"

      - run: ./mill -i __.compile

      - save_cache:
          paths:
            - ~/.ivy2/cache
            - ~/.m2
            - ~/.mill
            - ~/.cache/coursier
            - ~/.cache/mill
          key: "bla-{{ .Revision }}"

      - persist_to_workspace:
          root: "~"
          paths: project


  build2:
    executor: small
    steps:

      - attach_workspace:
          at: "~"

      - restore_cache:
          keys:
            - "bla-{{ .Revision }}"

      - run: ./mill -i __.compile


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - build2:
          requires:
            - build
